@url = http://localhost:21120

### Step 1: Get the list of recommendations for improving a prompt
POST {{url}}/chat
Content-Type: application/json
x-grid: 8091

{
  "sessionId": "123",
  "promptId": "chat_prompt:truefoundry/new-repo/tutor_prompt:1",
  "type": "validation",
  "recommendations": null,
  "data": null,
  "additionalData": null
}

### Step 2: Get the updated prompt after applying recommendations
POST {{url}}/microservices/x42-prompt-validator/v1/chat
Content-Type: application/json

{
  "sessionId": "123",
  "promptId": "chat_prompt:truefoundry/new-repo/tutor_prompt:1",
  "type": "validation",
  "recommendations": [
          "Consider adding a sentence or two elaborating on the importance of accurate date extraction in a pharmaceutical context (e.g., medication safety, patient records).",
          "Reiterate the importance of handling Personally Identifiable Information (PII) with care and in compliance with privacy regulations."
        ],
  "data": null,
  "additionalData": null
}

### Step 5: Verify the test cases for a prompt
POST {{url}}/microservices/x42-prompt-validator/v1/chat
Content-Type: application/json
x-grid: 8091

{
  "sessionId": "123",
  "promptId": "chat_prompt:truefoundry/new-repo/tutor_prompt:1",
  "type": "verify_tests",
  "recommendations": null,
  "data": null,
  "additionalData": null
}

### Step 5 for exact match: Verify test cases for exact match functionality
POST http://0.0.0.0:21120/microservices/x42-prompt-validator/v1/chat
Content-Type: application/json
x-grid: 8091

{
  "sessionId": "123",
  "promptId": "chat_prompt:truefoundry/new-repo/tutor_prompt:1",
  "type": "verify_tests",
  "recommendations": null,
  "data": null,
  "additionalData": null
}
