"""LLM-as-a-Judge evaluator: compares original vs enhanced prompt outputs."""

import asyncio
import json

from src.chat.graph.base_evaluator import PromptEvaluator
from src.common.service.llm_prompt.prompt_service import PromptService
from src.common.service.logging.logger import info

# ── Metric catalogue ─────────────────────────────────────────────────────────

AVAILABLE_METRICS: dict[str, str] = {
    # General quality (default)
    "clarity":                    "How clear, well-structured, and easy to understand is the response?",
    "completeness":               "How thoroughly does it address the user's request?",
    "accuracy":                   "How factually correct and relevant is the content? For subjective tasks, evaluate internal consistency and relevance.",
    "conciseness":                "Is it appropriately concise without losing important detail?",
    "professional_tone":          "How professional and contextually appropriate is the tone?",
    # Guardrails / Classification
    "output_format_compliance":   "Does the response strictly follow the required output format or schema?",
    "hallucination_avoidance":    "Did it avoid making up facts, policies, or services that do not exist?",
    # Conversational
    "answer_relevance":           "Is the response directly relevant to what the user asked?",
    "prompt_instruction_adherence": "Did the model follow all rules and instructions stated in the system prompt?",
    "empathy_tone":               "Is the tone appropriately empathetic and contextually fitting for the user's situation?",
}

DEFAULT_METRICS: list[str] = [
    "clarity", "completeness", "accuracy", "conciseness", "professional_tone"
]

# Ordered for display (All_METRIC_KEYS is the canonical order used by the UI)
ALL_METRIC_KEYS: list[str] = list(AVAILABLE_METRICS.keys())


def build_judge_prompt(metrics: list[str]) -> str:
    """Build a judge system prompt dynamically from selected metric keys."""
    valid = [m for m in metrics if m in AVAILABLE_METRICS]
    if not valid:
        valid = DEFAULT_METRICS

    metric_lines = "\n".join(f"- {m}: {AVAILABLE_METRICS[m]}" for m in valid)
    json_fields = "\n".join(f'    "{m}": 0.0,' for m in valid)
    exact_keys = ", ".join(f'"{m}"' for m in valid)

    return f"""You are an expert prompt engineer and evaluator. You are given:
- The original and enhanced system prompts that were used to generate the responses
- A user input
- Response A generated by the original system prompt
- Response B generated by the enhanced system prompt

Your job: score both responses on the specified quality metrics and identify the key observable differences between them.

### Scoring Rubric (0.0 to 1.0 scale)
- 0.0: Fails to meet any requirements or is completely irrelevant.
- 0.5: Meets basic requirements and is acceptable.
- 1.0: Exceeds all expectations, providing exceptional quality and insight.

### Metrics
Score each response on these metrics:
{metric_lines}

### Calculation and Logic Rules
- The 'overall' score MUST be the exact mathematical average of all metric scores. Do not provide a subjective total.
- Use the system prompts as ground truth when evaluating metrics like output_format_compliance and prompt_instruction_adherence.
- Fallback: If Response A and Response B are identical, assign identical scores to both and note this in 'improvement_summary'.

### Key Differences
Identify the most notable observable differences between Response A and Response B in terms of style, structure, content coverage, or phrasing. These are factual comparisons, not judgements.

### Output Constraints
Return ONLY valid JSON. Do NOT include markdown code fences, conversational filler, or any text outside the JSON object.
CRITICAL: The JSON keys inside "original" and "enhanced" MUST be EXACTLY: {exact_keys} plus "overall". Do NOT add, rename, or omit any metric keys.

Format:
{{
  "original": {{
{json_fields}
    "overall": 0.0
  }},
  "enhanced": {{
{json_fields}
    "overall": 0.0
  }},
  "improved": true,
  "improvement_summary": "One sentence summary of whether and how quality improved.",
  "key_differences": [
    "Concrete factual difference between Response A and Response B.",
    "Another observable difference."
  ]
}}"""


_JUDGE_USER_TEMPLATE = """Original System Prompt:
{original_system_prompt}

Enhanced System Prompt:
{enhanced_system_prompt}

---

User Input:
{input}

Response A (Original Prompt Output):
{original_output}

Response B (Enhanced Prompt Output):
{enhanced_output}"""


class LLMJudgeEvaluator(PromptEvaluator):
    """Evaluator that uses an LLM as a judge to compare original vs enhanced outputs."""

    def __init__(self, *args, judge_system_prompt_override: str | None = None, **kwargs):
        super().__init__(*args, **kwargs)
        self._judge_system_prompt_override = judge_system_prompt_override

    async def get_test_responses_both(
        self,
        all_tests: list[dict],
        original_system_prompt: str,
        enhanced_system_prompt: str,
        user_prompt_template: str | None,
        enhanced_model_name: str | None = None,
        enhanced_temperature: float | None = None,
        enhanced_max_tokens: int | None = None,
        enhanced_reasoning_effort: str | None = None,
    ) -> list[dict]:
        """Get LLM responses for both prompts in parallel for each test case.

        Original prompt uses self.model_name/temperature/etc.
        Enhanced prompt uses enhanced_* overrides when provided, falling back to self.* values.
        Both fire concurrently via asyncio.gather — different models do not serialise execution.
        """
        enh_model = enhanced_model_name or self.model_name
        enh_temp = enhanced_temperature if enhanced_temperature is not None else self.temperature
        enh_tokens = enhanced_max_tokens or self.max_tokens
        enh_effort = enhanced_reasoning_effort or self.reasoning_effort

        sem = asyncio.Semaphore(5)

        async def _timed_call(coro):
            t = asyncio.get_running_loop().time()
            result = await coro
            return result, round(asyncio.get_running_loop().time() - t, 2)

        async def get_pair(test: dict) -> dict:
            async with sem:
                (orig, orig_lat), (enh, enh_lat) = await asyncio.gather(
                    _timed_call(PromptService.get_prompt_response_from_text(
                        system_prompt=original_system_prompt,
                        user_prompt_template=user_prompt_template,
                        data=test["data"],
                        model_name=self.model_name,
                        max_tokens=self.max_tokens,
                        temperature=self.temperature,
                        reasoning_effort=self.reasoning_effort,
                    )),
                    _timed_call(PromptService.get_prompt_response_from_text(
                        system_prompt=enhanced_system_prompt,
                        user_prompt_template=user_prompt_template,
                        data=test["data"],
                        model_name=enh_model,
                        max_tokens=enh_tokens,
                        temperature=enh_temp,
                        reasoning_effort=enh_effort,
                    )),
                )
            test["original_output"] = orig
            test["enhanced_output"] = enh
            test["original_latency_s"] = orig_lat
            test["enhanced_latency_s"] = enh_lat
            return test

        return list(await asyncio.gather(*[get_pair(t) for t in all_tests]))

    async def _judge_single(
        self,
        test: dict,
        metrics: list[str],
        original_system_prompt: str = "",
        enhanced_system_prompt: str = "",
    ) -> dict:
        """Run the LLM judge on a single test case."""
        judge_prompt = self._judge_system_prompt_override or build_judge_prompt(metrics)
        info(f"[JUDGE_SINGLE] test_id={test.get('test_case_id')} | metrics={metrics} | input_len={len(str(test.get('data', {}).get('input', '')))}")

        user_msg = _JUDGE_USER_TEMPLATE.format(
            original_system_prompt=original_system_prompt or "(not provided)",
            enhanced_system_prompt=enhanced_system_prompt or "(not provided)",
            input=test["data"]["input"],
            original_output=test["original_output"],
            enhanced_output=test["enhanced_output"],
        )
        raw = await PromptService.get_prompt_response_from_text(
            system_prompt=judge_prompt,
            user_prompt_template=None,
            data={"input": user_msg},
            model_name=self.model_name,
            max_tokens=self.max_tokens,
            temperature=0.0,
            reasoning_effort=self.reasoning_effort,
        )
        try:
            cleaned = raw.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[-1]
                cleaned = cleaned.rsplit("```", 1)[0]
            scores = json.loads(cleaned.strip())
            info(f"[JUDGE_SINGLE] test_id={test.get('test_case_id')} | orig_overall={scores.get('original', {}).get('overall')} | enh_overall={scores.get('enhanced', {}).get('overall')} | improved={scores.get('improved')}")
        except (json.JSONDecodeError, IndexError):
            info(f"[JUDGE_SINGLE] test_id={test.get('test_case_id')} | parse_error=true | raw_len={len(raw)}")
            scores = {"error": "Failed to parse judge response", "raw": raw}

        return {
            "test_case_id": test.get("test_case_id"),
            "test_case_name": test.get("test_case_name", ""),
            "input": test["data"]["input"],
            "original_output": test["original_output"],
            "enhanced_output": test["enhanced_output"],
            "scores": scores,
            "original_latency_s": test.get("original_latency_s"),
            "enhanced_latency_s": test.get("enhanced_latency_s"),
        }

    async def evaluate_tests(
        self,
        all_tests: list[dict],
        is_rag: bool = False,
        metrics: list[str] | None = None,
        original_system_prompt: str = "",
        enhanced_system_prompt: str = "",
    ) -> list[dict]:
        active_metrics = metrics or DEFAULT_METRICS
        sem = asyncio.Semaphore(5)

        async def _judge_with_sem(t):
            async with sem:
                return await self._judge_single(
                    t,
                    metrics=active_metrics,
                    original_system_prompt=original_system_prompt,
                    enhanced_system_prompt=enhanced_system_prompt,
                )

        return list(await asyncio.gather(*[_judge_with_sem(t) for t in all_tests]))

    def get_final_report(
        self,
        all_tests: list[dict],
        evaluation_results: list[dict],
        requested_metrics: list[str] | None = None,
    ) -> dict:
        # Use requested metrics as authoritative; infer from response only as fallback
        if requested_metrics:
            metrics = [m for m in requested_metrics if m in AVAILABLE_METRICS]
        else:
            first_scores = next(
                (r.get("scores", {}) for r in evaluation_results if "error" not in r.get("scores", {})),
                {},
            )
            metrics = [k for k in first_scores.get("original", {}).keys() if k != "overall"]
        if not metrics:
            metrics = DEFAULT_METRICS

        agg_orig = {m: [] for m in metrics + ["overall"]}
        agg_enh = {m: [] for m in metrics + ["overall"]}
        improved_count = 0

        for r in evaluation_results:
            scores = r.get("scores", {})
            if "error" in scores:
                continue
            for m in metrics + ["overall"]:
                orig_val = scores.get("original", {}).get(m)
                enh_val = scores.get("enhanced", {}).get(m)
                if orig_val is not None:
                    agg_orig[m].append(orig_val)
                if enh_val is not None:
                    agg_enh[m].append(enh_val)
            if scores.get("improved"):
                improved_count += 1

        def avg(lst):
            return round(sum(lst) / len(lst), 3) if lst else None

        display_metrics = metrics + ["overall"]
        return {
            "test_results": evaluation_results,
            "metrics_used": metrics,
            "metrics_requested": metrics,
            "summary": {
                "total_cases": len(evaluation_results),
                "improved_count": improved_count,
                "avg_original": {m: avg(agg_orig[m]) for m in display_metrics},
                "avg_enhanced": {m: avg(agg_enh[m]) for m in display_metrics},
                "avg_delta": {
                    m: round(avg(agg_enh[m]) - avg(agg_orig[m]), 3)
                    if avg(agg_enh[m]) is not None and avg(agg_orig[m]) is not None
                    else None
                    for m in display_metrics
                },
            },
        }

    async def verify_tests(self, state: dict) -> dict:
        original_system_prompt = state["request"].get("system_prompt", "")
        enhanced_system_prompt = state["request"].get("enhanced_system_prompt", "")
        user_prompt_template = state["request"].get("user_prompt_template")
        metrics = state["request"].get("judge_metrics") or DEFAULT_METRICS

        enhanced_model_name = state["request"].get("enhanced_model_name")
        enhanced_temperature = state["request"].get("enhanced_temperature")
        enhanced_max_tokens = state["request"].get("enhanced_max_tokens")
        enhanced_reasoning_effort = state["request"].get("enhanced_reasoning_effort")

        provided_tests = state["request"].get("test_cases")
        if not provided_tests:
            return {}

        info(f"LLM Judge: {len(provided_tests)} test cases | metrics={metrics} | enh_model={enhanced_model_name or 'same as original'}")
        all_tests = await self.get_test_responses_both(
            provided_tests,
            original_system_prompt,
            enhanced_system_prompt,
            user_prompt_template,
            enhanced_model_name=enhanced_model_name,
            enhanced_temperature=enhanced_temperature,
            enhanced_max_tokens=enhanced_max_tokens,
            enhanced_reasoning_effort=enhanced_reasoning_effort,
        )
        info("LLM Judge: responses collected for both prompts")

        evaluation_results = await self.evaluate_tests(
            all_tests,
            metrics=metrics,
            original_system_prompt=original_system_prompt,
            enhanced_system_prompt=enhanced_system_prompt,
        )
        info("LLM Judge: evaluation complete")

        report = self.get_final_report(all_tests, evaluation_results, requested_metrics=metrics)
        report["original_model"] = self.model_name or "default"
        report["enhanced_model"] = enhanced_model_name or self.model_name or "default"
        return report
